# Generated by Django 3.0.4 on 2020-03-08 21:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('couch', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('position', models.IntegerField(choices=[(0, 'Goalkeeper'), (1, 'Right Fullback'), (2, 'Left Fullback'), (3, 'Center Back'), (4, 'Sweeper'), (5, 'Defending Midfielder'), (6, 'Right Midfielder'), (7, 'Central'), (8, 'Striker'), (9, 'Attacking Midfielder'), (10, 'Left_midfielder')], default=0)),
                ('team', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='teams.Team')),
            ],
        ),
    ]
