# Generated by Django 3.0.4 on 2020-03-10 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='photo',
            field=models.ImageField(blank=True, default='team_default.jpg', null=True, upload_to='', verbose_name='Imágen de fondo'),
        ),
    ]
