# Generated by Django 3.0.4 on 2020-03-10 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_team_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='location',
            field=models.CharField(default='Max Giulia', max_length=255),
            preserve_default=False,
        ),
    ]
